//
//  Post.swift
//  CustomApp
//
//  Created by Maxson Yang on 5/2/18.
//  Copyright © 2018 wendy hua. All rights reserved.
//

import Foundation
import ARKit
import UIKit
import MapKit

/**Class creating an ARObject to be serialized.**/
class Post : NSObject, MKAnnotation {
    //coordinates of point
    var coordinate: CLLocationCoordinate2D
    
    //username of poster
    let username: String
    
    //date posted
    let date: Date
    
    //modelpath and texture path
    var imagePath: String
    
    //id generated by firebase
    let postID: String
    
    /**initialize an ARObject*/
    init(lat: Double, lon: Double, imagepath: String, id: String, timeInterval: TimeInterval, Username: String) {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss.A"
        self.date = NSDate(timeIntervalSince1970: timeInterval/1000) as Date
        self.coordinate = CLLocationCoordinate2D(latitude: lat, longitude: lon)
        self.imagePath = imagepath
        self.username = Username
        self.postID = id
    }
    
    func getlat() -> Double {
        return self.coordinate.latitude
    }
    
    func getlon() -> Double {
        return self.coordinate.longitude
    }
    
    func getImage() -> String {
        return self.imagePath
    }
    func getTimeElapsedString() -> String {
        let secondsSincePosted = -date.timeIntervalSinceNow
        let minutes = Int(secondsSincePosted / 60)
        if minutes == 1 {
            return "\(minutes) minute ago"
        } else if minutes < 60 {
            return "\(minutes) minutes ago "
        } else if minutes < 120 {
            return "1 hour ago"
        } else if minutes < 24 * 60 {
            return "\(minutes / 60) hours ago"
        } else if minutes < 48 * 60 {
            return "1 day ago"
        } else {
            return "\(minutes / 1440) days ago"
        }
        
    }
}
